#remote_theme: pages-themes/time-machine@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-minimal
title: puheterapiaa
description: Puheterapiaa paikallisesti Helsingiss√§.

github:
  is_project_page: false
